controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
location:
    path: ../location

measurement:
    path: ../measurement

app_logout:
    path: /logout
    methods: GET